#python proposed_tethering_setup_script.py --fasta 'cggggccccauacaaugacggaucgaaauccguuugacgcacggccuggc gagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccg' --secstruct '(((((((((((((......((((((((((((.......((((((((((.( ).....)))).))))))...))))))))))))......)))))))))))))' --pdbs '../pdbs/3R8S.pdb ../pdbs/4GD1.pdb' --bps 'A2854-A2863 A1445-A1457' --execute true
#python proposed_tethering_setup_script.py --fasta 'cggggccccauacaaugacggaucgaaauccguuugacgcacggccuggc gagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccg' --secstruct '(((((((((((((......((((((((((((.......((((((((((.( ).....)))).))))))...))))))))))))......)))))))))))))' --pdbs '../pdbs/4GD1.pdb ../pdbs/3R8S.pdb' --bps 'A1445-A1457 A2854-A2863' --execute true
#python proposed_tethering_setup_script.py --fasta 'cggggccccauacaaugacggaucgaaauccguuugacgcacggccuggc gagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccg' --secstruct '(((((((((((((......((((((((((((.......((((((((((.( ).....)))).))))))...))))))))))))......)))))))))))))' --pdbs '../pdbs/4GD1.pdb ../pdbs/3R8S.pdb' --bps 'A1449-A1454 A2854-A2863' --execute true
#python proposed_tethering_setup_script.py --fasta 'cggggccccauacaaugacggaucgaaauccguuugacgcacggccuggc gagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccg' --secstruct '(((((((((((((......((((((((((((.......((((((((((.( ).....)))).))))))...))))))))))))......)))))))))))))' --pdbs '../pdbs/4GD1.pdb ../pdbs/3R8S.pdb' --bps 'A1445-A1457 A2853-A2864' --execute true


# This assumes the BPs were included in the provided sequence from google doc. Otherwise...
#python proposed_tethering_setup_script.py --fasta 'cggggccccauacaaugacggaucgaaauccguuugacgcacggccuggc gagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccg' --secstruct '(((((((((((((......((((((((((((.......((((((((((.( ).....)))).))))))...))))))))))))......)))))))))))))' --pdbs '../pdbs/4GD1.pdb ../pdbs/3R8S.pdb' --bps 'A1445-A1457 A2864-A2853' --execute true

python proposed_tethering_setup_script.py --fasta 'ucggggccccauacaaugacggaucgaaauccguuugacgcacggccuggcc ggagcaacagguccgugccgaggauuucgaucuaagacaguauggggccccgg' --secstruct '((((((((((((((......((((((((((((.......((((((((((.(( )).....)))).))))))...))))))))))))......))))))))))))))' --pdbs '../pdbs/4GD1.pdb ../pdbs/3R8S.pdb' --bps 'A1445-A1457 A2864-A2853' --execute true --whole_ribosome true
